window.SKILL_CATALOG = [
  {
    id: "oil-motion",
    name: "Oil Motion",
    subtitle: "把滚动，变成一段故事",
    category: "网页设计",
    categoryKey: "web",
    description: "将滚动、拖拽等交互意图转换为动效方案、动画素材与网页运行时，明确画面如何推进、停住和退回。",
    input: "页面用途、主体与风格、交互方式、目标设备，以及已有图片或视频。",
    output: ["视觉与交互方案", "关键帧及动画生产计划", "素材时间轴与网页运行时"],
    requirements: ["生成与处理素材需要 Python 3、Pillow、ffmpeg 和 ffprobe。", "视频生成需要配置相应模型服务。", "下载提供 SKILL.md 单文件预览；完整流程还需要配套 scripts、references 和 assets。"],
    example: "使用 oil-motion，为公开 Skill 集合网站设计档案抽屉随滚动打开的动效，停止滚动时定格，向上滚动时退回。",
    icon: "spark",
    sourceLabel: "oil-oil/oil-motion",
    sourceUrl: "https://github.com/oil-oil/oil-motion",
    fileName: "skills/oil-motion/SKILL.md"
  },
  {
    id: "seedance-prompt-engineer",
    name: "Seedance 提示词工程师",
    subtitle: "把创意，写成可拍的分镜",
    category: "视频创作",
    categoryKey: "video",
    description: "根据模型版本、素材和叙事目标选择生成或编辑模式，输出中文视频提示词、分镜与素材映射。",
    input: "视频主题、Seedance 版本、目标时长与画幅，以及图片、视频、音频等参考素材。",
    output: ["视频制作方案", "素材用途与作用范围", "可复制的中文提示词或编辑指令"],
    requirements: ["实际生成视频需要使用即梦或 Seedance 平台。", "本地提示词校验需要 Python 和配套校验脚本。", "下载提供 SKILL.md 单文件预览；完整流程还需要配套 references 和 scripts。"],
    example: "使用 Seedance 提示词工程师，为一杯冰咖啡设计 15 秒、9:16 的产品短视频，给出素材映射、分镜和可复制的中文提示词。",
    icon: "film",
    sourceLabel: "matutu-ai/seedance2.5-skill",
    sourceUrl: "https://github.com/matutu-ai/seedance2.5-skill",
    fileName: "skills/seedance-prompt-engineer/SKILL.md"
  },
  {
    id: "geo-keyword-persona",
    name: "GEO 画像选词",
    subtitle: "从用户问题，找到内容方向",
    category: "营销增长",
    categoryKey: "marketing",
    description: "围绕目标用户与决策阶段组织关键词，形成画像矩阵、语义集群、内容规划和信源建设清单。",
    input: "品牌或产品、所属行业、目标用户、业务目标、竞品与关注的 AI 搜索平台。",
    output: ["用户画像概览", "画像与阶段关键词矩阵", "内容规划与信源建设清单"],
    requirements: ["准备品牌与目标用户资料；缺失信息需要明确标注假设。", "效果评估需结合实际搜索与内容数据，不保证推荐结果。", "下载提供 SKILL.md 单文件预览；如使用其他参考资料，需自行补齐。"],
    example: "使用 GEO 画像选词，为面向中小企业运营团队的客服 SaaS 建立用户画像、关键词矩阵与内容规划；缺失资料请标注假设。",
    icon: "search",
    sourceLabel: "matutu-ai/GEO",
    sourceUrl: "https://github.com/matutu-ai/GEO",
    fileName: "skills/geo-keyword-persona/SKILL.md"
  },
  {
    id: "jewelry-luxury-brand-kit",
    name: "珠宝品牌制作包",
    subtitle: "让珠宝的光，有自己的叙事",
    category: "网页设计",
    categoryKey: "web",
    description: "围绕珠宝产品与品牌调性，制作 15 秒广告视频提示词、电影感单页方案，或对应的网页实现。",
    input: "珠宝类型、品牌名称与调性、产品图片，以及定价和页面文案。",
    output: ["15 秒珠宝广告视频提示词", "滚动驱动品牌单页方案", "视频与网站双交付制作包"],
    requirements: ["视频生成需要即梦、Seedance 等相应平台。", "网页实现采用 React 19、TypeScript、Vite 6 和 Tailwind CSS v4。", "下载提供 SKILL.md 单文件预览；完整模板还需要配套 references。"],
    example: "使用珠宝品牌制作包，为一枚天然蓝宝石戒指设计 15 秒、16:9、一镜到底的广告提示词，并给出配套品牌单页方案。",
    icon: "layout",
    sourceLabel: "matutu-ai/seedance2.5-skill",
    sourceUrl: "https://github.com/matutu-ai/seedance2.5-skill",
    fileName: "skills/jewelry-luxury-brand-kit/SKILL.md"
  },
  {
    id: "seedance-prompt-description",
    name: "Seedance 2.5 提示词描述",
    subtitle: "锁定人物，也锁定镜头节奏",
    category: "视频创作",
    categoryKey: "video",
    description: "用固定中文结构整理素材、人物、摄影、时间轴与声音，适合需要角色连续性和明确结束状态的视频项目。",
    input: "主题与时长、画幅、人物和场景参考、摄影风格，以及旁白或声音要求。",
    output: ["结构化视频提示词", "人物与摄影连续性约束", "时间轴及片段结束状态"],
    requirements: ["实际视频生成需要 Seedance 2.5 或即梦的相应能力。", "提示词校验依赖 seedance-prompt-engineer 的配套脚本与规格参考。", "下载提供 SKILL.md 单文件预览；完整示例还需要配套 references。"],
    example: "使用 Seedance 2.5 提示词描述，写一条 15 秒、9:16 的咖啡馆人物短片提示词，锁定人物服装，采用 DV 质感，无 BGM。",
    icon: "film",
    sourceLabel: "matutu-ai/seedance2.5-skill",
    sourceUrl: "https://github.com/matutu-ai/seedance2.5-skill",
    fileName: "skills/seedance-prompt-description/SKILL.md"
  },
  {
    id: "ai-promotion-summary",
    name: "AI 推广总结",
    subtitle: "让品牌词与业务词各司其职",
    category: "营销增长",
    categoryKey: "marketing",
    description: "按品牌、客群、服务和地域整理品牌词与业务词，并给出内容方向、信源一致性和监测建议。",
    input: "品牌全称、希望覆盖的搜索场景、目标客群、服务卖点与定位区域。",
    output: ["品牌词清单", "品类、地域、组合与问题词", "推广优先级与执行建议"],
    requirements: ["准备准确的品牌、地域和服务信息。", "实际推广效果需要持续监测，不保证平台推荐。", "下载提供 SKILL.md 单文件预览；如使用其他参考资料，需自行补齐。"],
    example: "使用 AI 推广总结，为面向上海初学者的成人钢琴工作室整理品牌词、业务词和内容建议；品牌暂用“示例钢琴工作室”。",
    icon: "search",
    sourceLabel: "matutu-ai/GEO",
    sourceUrl: "https://github.com/matutu-ai/GEO",
    fileName: "skills/ai-promotion-summary/SKILL.md"
  },
  {
    id: "agent-work-log",
    name: "代理商工作日报",
    subtitle: "把零散记录，整理成清晰成果",
    category: "效率办公",
    categoryKey: "office",
    description: "将原始服务与运营笔记归并为五段日报，保留代理商名称与事项细节，突出关键数据和待跟进工作。",
    input: "当天原始工作记录、处理进展、相关代理商名称、关键数据与明日待办。",
    output: ["今日核心成果与重点专项", "分类业务办结与问题复盘", "明日工作计划"],
    requirements: ["输入应包含真实处理状态，统计数据需要有记录依据。", "未办结事项应明确保留为待跟进。", "下载提供 SKILL.md 单文件预览；复杂日报示例还需要配套 references/template.md。"],
    example: "使用代理商工作日报，将下面的工作记录整理为五段高亮日报，保留全部代理商名称与问题细节，未办结事项放入待跟进计划。",
    icon: "file",
    sourceLabel: "matutu-ai/macos-obsidian",
    sourceUrl: "https://github.com/matutu-ai/macos-obsidian",
    fileName: "skills/agent-work-log/SKILL.md"
  }
];
